class Surah {
  final String name;
  final int verses;

  const Surah({
    required this.name,
    required this.verses,
  });
}

class QuranData {
  QuranData._();

  static const List<Surah> surahs = [
    Surah(name: 'الفاتحة', verses: 7),
    Surah(name: 'البقرة', verses: 286),
    Surah(name: 'آل عمران', verses: 200),
    Surah(name: 'النساء', verses: 176),
    Surah(name: 'المائدة', verses: 120),
    Surah(name: 'الأنعام', verses: 165),
    Surah(name: 'الأعراف', verses: 206),
    Surah(name: 'الأنفال', verses: 75),
    Surah(name: 'التوبة', verses: 129),
    Surah(name: 'يونس', verses: 109),
    Surah(name: 'هود', verses: 123),
    Surah(name: 'يوسف', verses: 111),
    Surah(name: 'الرعد', verses: 43),
    Surah(name: 'إبراهيم', verses: 52),
    Surah(name: 'الحجر', verses: 99),
    Surah(name: 'النحل', verses: 128),
    Surah(name: 'الإسراء', verses: 111),
    Surah(name: 'الكهف', verses: 110),
    Surah(name: 'مريم', verses: 98),
    Surah(name: 'طه', verses: 135),
    Surah(name: 'الأنبياء', verses: 112),
    Surah(name: 'الحج', verses: 78),
    Surah(name: 'المؤمنون', verses: 118),
    Surah(name: 'النور', verses: 64),
    Surah(name: 'الفرقان', verses: 77),
    Surah(name: 'الشعراء', verses: 227),
    Surah(name: 'النمل', verses: 93),
    Surah(name: 'القصص', verses: 88),
    Surah(name: 'العنكبوت', verses: 69),
    Surah(name: 'الروم', verses: 60),
    Surah(name: 'لقمان', verses: 34),
    Surah(name: 'السجدة', verses: 30),
    Surah(name: 'الأحزاب', verses: 73),
    Surah(name: 'سبأ', verses: 54),
    Surah(name: 'فاطر', verses: 45),
    Surah(name: 'يس', verses: 83),
    Surah(name: 'الصافات', verses: 182),
    Surah(name: 'ص', verses: 88),
    Surah(name: 'الزمر', verses: 75),
    Surah(name: 'غافر', verses: 85),
    Surah(name: 'فصلت', verses: 54),
    Surah(name: 'الشورى', verses: 53),
    Surah(name: 'الزخرف', verses: 89),
    Surah(name: 'الدخان', verses: 59),
    Surah(name: 'الجاثية', verses: 37),
    Surah(name: 'الأحقاف', verses: 35),
    Surah(name: 'محمد', verses: 38),
    Surah(name: 'الفتح', verses: 29),
    Surah(name: 'الحجرات', verses: 18),
    Surah(name: 'ق', verses: 45),
    Surah(name: 'الذاريات', verses: 60),
    Surah(name: 'الطور', verses: 49),
    Surah(name: 'النجم', verses: 62),
    Surah(name: 'القمر', verses: 55),
    Surah(name: 'الرحمن', verses: 78),
    Surah(name: 'الواقعة', verses: 96),
    Surah(name: 'الحديد', verses: 29),
    Surah(name: 'المجادلة', verses: 22),
    Surah(name: 'الحشر', verses: 24),
    Surah(name: 'الممتحنة', verses: 13),
    Surah(name: 'الصف', verses: 14),
    Surah(name: 'الجمعة', verses: 11),
    Surah(name: 'المنافقون', verses: 11),
    Surah(name: 'التغابن', verses: 18),
    Surah(name: 'الطلاق', verses: 12),
    Surah(name: 'التحريم', verses: 12),
    Surah(name: 'الملك', verses: 30),
    Surah(name: 'القلم', verses: 52),
    Surah(name: 'الحاقة', verses: 52),
    Surah(name: 'المعارج', verses: 44),
    Surah(name: 'نوح', verses: 28),
    Surah(name: 'الجن', verses: 28),
    Surah(name: 'المزمل', verses: 20),
    Surah(name: 'المدثر', verses: 56),
    Surah(name: 'القيامة', verses: 40),
    Surah(name: 'الإنسان', verses: 31),
    Surah(name: 'المرسلات', verses: 50),
    Surah(name: 'النبأ', verses: 40),
    Surah(name: 'النازعات', verses: 46),
    Surah(name: 'عبس', verses: 42),
    Surah(name: 'التكوير', verses: 29),
    Surah(name: 'الانفطار', verses: 19),
    Surah(name: 'المطففين', verses: 36),
    Surah(name: 'الانشقاق', verses: 25),
    Surah(name: 'البروج', verses: 22),
    Surah(name: 'الطارق', verses: 17),
    Surah(name: 'الأعلى', verses: 19),
    Surah(name: 'الغاشية', verses: 26),
    Surah(name: 'الفجر', verses: 30),
    Surah(name: 'البلد', verses: 20),
    Surah(name: 'الشمس', verses: 15),
    Surah(name: 'الليل', verses: 21),
    Surah(name: 'الضحى', verses: 11),
    Surah(name: 'الشرح', verses: 8),
    Surah(name: 'التين', verses: 8),
    Surah(name: 'العلق', verses: 19),
    Surah(name: 'القدر', verses: 5),
    Surah(name: 'البينة', verses: 8),
    Surah(name: 'الزلزلة', verses: 8),
    Surah(name: 'العاديات', verses: 11),
    Surah(name: 'القارعة', verses: 11),
    Surah(name: 'التكاثر', verses: 8),
    Surah(name: 'العصر', verses: 3),
    Surah(name: 'الهمزة', verses: 9),
    Surah(name: 'الفيل', verses: 5),
    Surah(name: 'قريش', verses: 4),
    Surah(name: 'الماعون', verses: 7),
    Surah(name: 'الكوثر', verses: 3),
    Surah(name: 'الكافرون', verses: 6),
    Surah(name: 'النصر', verses: 3),
    Surah(name: 'المسد', verses: 5),
    Surah(name: 'الإخلاص', verses: 4),
    Surah(name: 'الفلق', verses: 5),
    Surah(name: 'الناس', verses: 6),
  ];
}
